version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: travel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: travelmanagement
      MYSQL_USER: traveluser
      MYSQL_PASSWORD: travelpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - travel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./travel-backend
    container_name: travel-backend
    ports:
      - "8080:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/travelmanagement
      - SPRING_DATASOURCE_USERNAME=traveluser
      - SPRING_DATASOURCE_PASSWORD=travelpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - travel-network

volumes:
  mysql_data:
    driver: local

networks:
  travel-network:
    driver: bridge
